title: Gunawan Coding
author: GitHub User
email: gunawancoding@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog github ini saya gunakan untuk membagi ilmu mengenai proyek program yang saya buat.
  Fokus saya adalah Kotlin Android Studio, Dart Flutter, Node JS BackEnd, React JS Front End.
  Silahkan yang ingin bertukar pikiran dan diskusi mengenai programming.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
